name: flutter_multi_selection_medium
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx:
  mobx:
  flutter_modular: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true